#
# Settings for Ariadne Server Module
#
# NOTICE:
# When deploying
#   for prod/staging comment IN ariaden-client service
#   for develpment comment OUT ariadne-client service
#


version: '3'

services:
  ariadne-server:
    build:
      context: .
      dockerfile: server/docker/server.dockerfile
    working_dir: /var/www/html
    volumes:
      - ./server/:/var/www/
    ports:
      - 8080:80